version: '3.6'
services:

  apigw:
    container_name: apigw
    build:
      context: ./gateway
      dockerfile: Dockerfile.gw.dev
    ports:
      - "1323:1323"
    volumes:
      - ./gateway:/app
    depends_on:
      db:
        condition: service_healthy
    tty: true
    restart: always

  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_info
    ports:
      - '5432:5432'
    volumes:
      - ./common/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

networks:
  default:
    driver: bridge