version: '3.6'
services:

  gw:
    container_name: gw
    build:
      context: ./gateway
      dockerfile: Dockerfile.gw.dev
    ports:
      - "9323:1323"
    volumes:
      - ./gateway:/app
    depends_on:
      db:
        condition: service_healthy
      apis:
        condition: service_healthy
    tty: true
    restart: always

  apis:
    container_name: apis
    build:
      context: ./apis
      dockerfile: Dockerfile.api.dev
    ports:
      - 1323
    volumes:
      - ./apis:/app
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: "curl --fail http://localhost:1323/health || exit 1"
      interval: 30s
      timeout: 30s
      retries: 5
      # start_period: 30s # delay 30s
    tty: true
    restart: always

  db:
    container_name: db
    image: postgres
    environment:
      TZ: 'GMT+7'
      PGTZ: 'GMT+7'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_info
    ports:
      - '5432:5432'
    volumes:
      - ./common/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

networks:
  default:
    driver: bridge