# syntax=docker/dockerfile:1

FROM golang:1.18-buster AS build

WORKDIR /app

ENV TZ Asia/Bangkok

COPY go.mod ./
COPY go.sum ./
RUN go mod download && \
    go install github.com/cosmtrek/air@latest

COPY . .
RUN chmod +x /app

EXPOSE 1323

ENTRYPOINT [ "air" ]