FROM node:18-alpine

ENV NEXT_TELEMETRY_DISABLED 1

WORKDIR /app
COPY package.json .

RUN npm install -g pnpm && \
    pnpm i
    
COPY . .

EXPOSE 3001

CMD ["pnpm", "run", "dev"]
# CMD ["pnpm", "run", "dev:turbo"]